<?php 
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_overview',
		'title' => 'Overview',
		'fields' => array (
			array (
				'key' => 'field_527d5d1cfb84f',
				'label' => 'Client',
				'name' => 'client',
				'type' => 'text',
				'instructions' => 'Name of the client or project',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52c46fa974b08',
				'label' => 'Automatic Progress',
				'name' => 'automatic_progress',
				'type' => 'checkbox',
				'instructions' => 'Automatically calculate progress based on completion of phases (below)',
				'choices' => array (
					'Yes' => 'Yes',
				),
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_527d5d61fb854',
				'label' => 'Percent Complete',
				'name' => 'percent_complete',
				'type' => 'num_slider',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52c46fa974b08',
							'operator' => '!=',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'minimum_number' => 1,
				'max_number' => 100,
				'inc_number' => 1,
				'start_number' => '',
			),
			array (
				'key' => 'field_52a9e43c4b145',
				'label' => 'Project Details',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_527d5d3cfb851',
				'label' => 'Project Description',
				'name' => 'project_description',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_527d5d4afb852',
				'label' => 'Start Date',
				'name' => 'start_date',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 0,
			),
			array (
				'key' => 'field_527d5d57fb853',
				'label' => 'End Date',
				'name' => 'end_date',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 0,
			),
			array (
				'key' => 'field_52a9e4594b146',
				'label' => 'Documents',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52a9e4634b147',
				'label' => 'Documents',
				'name' => 'documents',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_52a9e4774b148',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_52a9e47f4b149',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_52a9e4964b14a',
						'label' => 'File',
						'name' => 'file',
						'type' => 'file',
						'column_width' => '',
						'save_format' => 'object',
						'library' => 'all',
					),
					array (
						'key' => 'field_52a9e49e4b14b',
						'label' => 'Status',
						'name' => 'status',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'Approved' => 'Approved',
							'In Review' => 'In Review',
							'Revisions' => 'Revisions',
							'Rejected' => 'Rejected',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Document',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'psp_projects',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_milestones',
		'title' => 'Milestones',
		'fields' => array (
			array (
				'key' => 'field_53138cd18335f',
				'label' => 'Milestones',
				'name' => '',
				'type' => 'message',
				'message' => 'If desired, describe what will be completed at key points in the project.',
			),
			array (
				'key' => 'field_528170f6552e1',
				'label' => 'Display Milestones',
				'name' => 'display_milestones',
				'type' => 'checkbox',
				'choices' => array (
					'Yes' => 'Yes',
				),
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_52817036552d8',
				'label' => 'Milestone Frequency',
				'name' => 'milestone_frequency',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'null' => '---',
					'quarters' => '25% / 50% / 75%',
					'fifths' => '20% / 40% / 60% / 80%',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a9e020fba90',
				'label' => '1st Milestone',
				'name' => '',
				'type' => 'tab',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_53138d853bbf8',
				'label' => 'Note:',
				'name' => '',
				'type' => 'message',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '!=',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'message' => 'If you\'d like to label key milestones please turn "Display Milestones" on (above).',
			),
			array (
				'key' => 'field_5281706e552d9',
				'label' => 'Title',
				'name' => '25%_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_528170a1552da',
				'label' => 'Description',
				'name' => '25%_description',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_52a9e067fba92',
				'label' => '2nd Milestone',
				'name' => '',
				'type' => 'tab',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_53138db13bbf9',
				'label' => 'Note:',
				'name' => '',
				'type' => 'message',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '!=',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
			),
			array (
				'key' => 'field_528170ac552db',
				'label' => 'Title',
				'name' => '50%_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_528170b6552dc',
				'label' => 'Description',
				'name' => '50%_description',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_52a9e084fba93',
				'label' => '3rd Milestone',
				'name' => '',
				'type' => 'tab',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_53138dbe3bbfa',
				'label' => 'Note: ',
				'name' => '',
				'type' => 'message',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '!=',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
			),
			array (
				'key' => 'field_528170c2552dd',
				'label' => 'Title',
				'name' => '75%_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_528170cc552de',
				'label' => 'Description',
				'name' => '75%_description',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_52a9e03afba91',
				'label' => '4th Milestone',
				'name' => '',
				'type' => 'tab',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
						array (
							'field' => 'field_52817036552d8',
							'operator' => '==',
							'value' => 'fifths',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_53138dcc3bbfb',
				'label' => 'Note:',
				'name' => '',
				'type' => 'message',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '!=',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
			),
			array (
				'key' => 'field_53138d1583360',
				'label' => 'Note:',
				'name' => '',
				'type' => 'message',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52817036552d8',
							'operator' => '==',
							'value' => 'quarters',
						),
					),
					'allorany' => 'all',
				),
				'message' => 'These fields are only available if you select "Fifths" on the milestone frequency field.',
			),
			array (
				'key' => 'field_528170db552df',
				'label' => 'Title',
				'name' => '100%_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
						array (
							'field' => 'field_52817036552d8',
							'operator' => '==',
							'value' => 'fifths',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_528170e6552e0',
				'label' => 'Description',
				'name' => '100%_description',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_528170f6552e1',
							'operator' => '==',
							'value' => 'Yes',
						),
						array (
							'field' => 'field_52817036552d8',
							'operator' => '==',
							'value' => 'fifths',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'psp_projects',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_phases',
		'title' => 'Phases',
		'fields' => array (
			array (
				'key' => 'field_531390350cb34',
				'label' => 'Phases',
				'name' => '',
				'type' => 'message',
				'message' => 'Phases let you define individual sections of a project, each with their own overall progress and tasks. For example, when redesigning a website you might have "Design, Development and Launch" phases.',
			),
			array (
				'key' => 'field_527d5dc12fa29',
				'label' => 'Phases',
				'name' => 'phases',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_527d5dd02fa2a',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_52c46f3fcf957',
						'label' => 'Automatic Progress',
						'name' => 'auto_progress',
						'type' => 'checkbox',
						'instructions' => 'Automatically calculate percentage complete based on tasks',
						'column_width' => '',
						'choices' => array (
							'Yes' => 'Yes',
						),
						'default_value' => '',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_53207ecf069ca',
						'label' => 'Weighting',
						'name' => 'weighting',
						'type' => 'checkbox',
						'instructions' => 'Does this phase take less time than the others?',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_52c46f3fcf957',
									'operator' => '==',
									'value' => 'Yes',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'Yes' => 'Yes',
						),
						'default_value' => '',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_53207efc069cb',
						'label' => 'Weight',
						'name' => 'weight',
						'type' => 'select',
						'instructions' => 'Specify how much shorter this phase is compared to the rest, i.e. selecting 95% will reduce this phases contribution to the total completion by 5%',
						'required' => 1,
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53207ecf069ca',
									'operator' => '==',
									'value' => 'Yes',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'.95' => '95%',
							'.90' => '90%',
							'.85' => '85%',
							'.80' => '80%',
							'.75' => '75%',
							'.70' => '70%',
							'.65' => '65%',
							'.60' => '60%',
							'.55' => '55%',
							'.50' => '50%',
							'.45' => '45%',
							'.40' => '40%',
							'.35' => '35%',
							'.30' => '30%',
							'.25' => '25%',
							'.20' => '20%',
							'.15' => '15%',
							'.10' => '10%',
							'.05' => '5%',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_527d5dd82fa2b',
						'label' => 'Percent Complete',
						'name' => 'percent_complete',
						'type' => 'select',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_52c46f3fcf957',
									'operator' => '!=',
									'value' => 'Yes',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							0 => '0%',
							5 => '5%',
							10 => '10%',
							15 => '15%',
							20 => '20%',
							25 => '25%',
							30 => '30%',
							35 => '35%',
							40 => '40%',
							45 => '45%',
							50 => '50%',
							55 => '55%',
							60 => '60%',
							65 => '65%',
							70 => '70%',
							75 => '75%',
							80 => '80%',
							85 => '85%',
							90 => '90%',
							95 => '95%',
							100 => '100%',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_527d5dea2fa2c',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
					array (
						'key' => 'field_527d5dfd2fa2d',
						'label' => 'Tasks',
						'name' => 'tasks',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_527d5e072fa2e',
								'label' => 'Task',
								'name' => 'task',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_527d5e0e2fa2f',
								'label' => 'Completion',
								'name' => 'status',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									0 => '0%',
									10 => '10%',
									15 => '15%',
									20 => '20%',
									25 => '25%',
									30 => '35%',
									40 => '40%',
									45 => '45%',
									50 => '50%',
									55 => '55%',
									60 => '60%',
									65 => '65%',
									70 => '70%',
									75 => '75%',
									80 => '80%',
									85 => '85%',
									90 => '90%',
									95 => '95%',
									100 => '100%',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add Task',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Phase',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'psp_projects',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 3,
	));
}

